import path from 'node:path';
import fs from 'node:fs/promises';
import crypto from 'node:crypto';
import { Router } from 'express';
import multer from 'multer';
import { z } from 'zod';
import { getDb, withTransaction } from './db.js';
import { exportGedcom, parseGedcom } from './gedcom.js';

const router = Router();
const uploadDir = path.resolve(process.env.UPLOAD_DIR || './data/uploads');
await fs.mkdir(uploadDir, { recursive: true });
const upload = multer({ dest: uploadDir, limits: { fileSize: 25 * 1024 * 1024 } });
const personSchema = z.object({ givenName: z.string().trim().min(1).max(100), surname: z.string().trim().max(100).optional().default(''), birthDate: z.string().max(40).optional(), birthPlace: z.string().max(200).optional(), deathDate: z.string().max(40).optional(), deathPlace: z.string().max(200).optional(), privacyStatus: z.enum(['private','tree_members','public']).optional() });
const relationSchema = z.object({ fromPersonId: z.string().uuid(), toPersonId: z.string().uuid(), relationType: z.enum(['parent','spouse','child','sibling']) });
const treeSchema = z.object({ name: z.string().trim().min(1).max(120), description: z.string().max(500).optional() });
function treeId(req) { return req.params.treeId; }
async function assertTree(ownerId, id) { const { rows } = await getDb().query('select * from trees where id=$1 and owner_id=$2', [id, ownerId]); if (!rows[0]) { const e = new Error('TREE_NOT_FOUND'); e.status = 404; throw e; } return rows[0]; }

router.get('/trees', async (req,res,next) => { try { const { rows } = await getDb().query('select * from trees where owner_id=$1 order by created_at desc', [req.user.id]); res.json({ trees: rows }); } catch(e){next(e);} });
router.post('/trees', async (req,res,next) => { try { const data=treeSchema.parse(req.body); const { rows }=await getDb().query('insert into trees(owner_id,name,description) values($1,$2,$3) returning *',[req.user.id,data.name,data.description||null]); res.status(201).json({tree:rows[0]}); } catch(e){ if(e instanceof z.ZodError)return res.status(400).json({error:'INVALID_INPUT',details:e.flatten()}); next(e); } });
router.get('/trees/:treeId/people', async(req,res,next)=>{try{await assertTree(req.user.id,treeId(req));const {rows}=await getDb().query(`select p.*, n.given_name,n.surname,n.maiden_name from persons p left join person_names n on n.person_id=p.id and n.is_primary=true where p.tree_id=$1 order by n.surname,n.given_name`,[treeId(req)]);res.json({people:rows});}catch(e){next(e);}});
router.post('/trees/:treeId/people', async(req,res,next)=>{try{await assertTree(req.user.id,treeId(req));const d=personSchema.parse(req.body);const person=await withTransaction(async c=>{const p=(await c.query('insert into persons(tree_id,privacy_status) values($1,$2) returning *',[treeId(req),d.privacyStatus||'tree_members'])).rows[0];await c.query('insert into person_names(person_id,given_name,surname) values($1,$2,$3)',[p.id,d.givenName,d.surname||'']);if(d.birthDate||d.birthPlace)await c.query("insert into events(tree_id,person_id,event_type,date_original,date_from,description) values($1,$2,'birth',$3,$4,$5)",[treeId(req),p.id,d.birthDate||null,d.birthDate?parseDate(d.birthDate):null,d.birthPlace||null]);return p;});res.status(201).json({person});}catch(e){if(e instanceof z.ZodError)return res.status(400).json({error:'INVALID_INPUT',details:e.flatten()});next(e);}});
router.get('/trees/:treeId/relationships',async(req,res,next)=>{try{await assertTree(req.user.id,treeId(req));const {rows}=await getDb().query('select * from relationships where tree_id=$1 order by created_at',[treeId(req)]);res.json({relationships:rows});}catch(e){next(e);}});
router.post('/trees/:treeId/relationships',async(req,res,next)=>{try{await assertTree(req.user.id,treeId(req));const d=relationSchema.parse(req.body);const {rows}=await getDb().query('insert into relationships(tree_id,from_person_id,to_person_id,relation_type) values($1,$2,$3,$4) returning *',[treeId(req),d.fromPersonId,d.toPersonId,d.relationType]);res.status(201).json({relationship:rows[0]});}catch(e){if(e instanceof z.ZodError)return res.status(400).json({error:'INVALID_INPUT',details:e.flatten()});next(e);}});
router.post('/trees/:treeId/import/gedcom',upload.single('file'),async(req,res,next)=>{try{await assertTree(req.user.id,treeId(req));if(!req.file)return res.status(400).json({error:'FILE_REQUIRED'});const parsed=parseGedcom(await fs.readFile(req.file.path));const result=await withTransaction(async c=>{const ids=new Map();for(const p of parsed.people){const [given,...rest]=(p.name||'Unknown').split('/');const name=given.trim();const surname=(rest[0]||'').trim();const person=(await c.query('insert into persons(tree_id) values($1) returning id',[treeId(req)])).rows[0];await c.query('insert into person_names(person_id,given_name,surname) values($1,$2,$3)',[person.id,name,surname]);ids.set(p.gedcomId,person.id);}let relations=0;for(const f of parsed.families){if(f.husband&&f.wife){const parentIds=[ids.get(f.husband),ids.get(f.wife)].filter(Boolean);for(const child of f.children){if(ids.get(child))for(const parent of parentIds){await c.query('insert into relationships(tree_id,from_person_id,to_person_id,relation_type) values($1,$2,$3,$4)',[treeId(req),parent,ids.get(child),'parent']);relations++;}}}}return {people:ids.size,relationships:relations};});await fs.rm(req.file.path,{force:true});res.status(201).json({imported:result});}catch(e){if(req.file)await fs.rm(req.file.path,{force:true}).catch(()=>{});next(e);}});
router.get('/trees/:treeId/export/gedcom',async(req,res,next)=>{try{await assertTree(req.user.id,treeId(req));const people=(await getDb().query('select p.id,n.given_name,n.surname,e.date_original as birth_date,e.description as birth_place from persons p left join person_names n on n.person_id=p.id and n.is_primary=true left join events e on e.person_id=p.id and e.event_type=\'birth\' where p.tree_id=$1',[treeId(req)])).rows;const relationships=(await getDb().query('select id,from_person_id,to_person_id from relationships where tree_id=$1',[treeId(req)])).rows;res.type('text/plain').attachment('gamlb-tree.ged').send(exportGedcom({people,relationships}));}catch(e){next(e);}});
router.post('/trees/:treeId/documents',upload.single('file'),async(req,res,next)=>{try{await assertTree(req.user.id,treeId(req));if(!req.file)return res.status(400).json({error:'FILE_REQUIRED'});const {personId}=req.body;const {rows}=await getDb().query('insert into documents(tree_id,person_id,original_name,stored_name,mime_type,size_bytes,storage_path) values($1,$2,$3,$4,$5,$6,$7) returning id,original_name,mime_type,size_bytes,created_at',[treeId(req),personId||null,req.file.originalname,req.file.filename,req.file.mimetype,req.file.size,req.file.path]);res.status(201).json({document:rows[0]});}catch(e){if(req.file)await fs.rm(req.file.path,{force:true}).catch(()=>{});next(e);}});
export default router;
function parseDate(v){const m=String(v||'').match(/(\d{4})/);return m?`${m[1]}-01-01`:null;}
